#
# This is the primary configuration file for your blog.
#


################################################################################
# Blog information
################################################################################


#
# The name of your blog.
#
name: Rassmalog


#
# Description of your blog.
#
info: |
  A static blog engine based on
      "YAML":http://www.yaml.org/,
      "eRuby":http://en.wikipedia.org/wiki/Eruby,
  and "Rake":http://rake.rubyforge.org/.


################################################################################
# Author information
################################################################################


#
# The name of the blog author.
#
author: Suraj N. Kurapati


#
# The e-mail address that will receive comments about your blog entries.
#
# This address will be obfuscated into HTML entities so that
# e-mail address harvesters won't bother to figure out what it
# is.  For example, the address "xxx@yyy.zzz" will be converted
# into the following *before* it is written to a HTML file:
#
# &#120;&#120;&#120;&#64;&#121;&#121;&#121;&#46;&#122;&#122;&#122;
#
# If you do not wish to receive comments about your
# blog entries, or if you absolutely *do not* want
# your e-mail address to be included in the output
# (even in the obfuscated form), then you can
# simply leave this parameter blank, as follows:
#
#   email:   # nothing here!
#
# Examples:
#
#   email: your@email.here
#   email: your+blog@email.here
#   email: your+comments@email.here
#
email: snk@gna.org


################################################################################
# Publishing information
################################################################################


#
# The URL of your published blog.
#
# Examples:
#
#   url: http://your_host.com/~you/path/to/your/blog/
#   url: http://you.your_host.com/path/to/your/blog/
#
url: http://rassmalog.rubyforge.org/output/


#
# An eRuby template for the command that uploads your blog to your website.
#
# The following predefined variables are available:
#
#   <%= whole %> is a path to the directory that must be uploaded.
#
#   <%= parts %> is a sequence of quoted paths to files that must be uploaded.
#                For example, the result of this directive is something like:
#
#                "output/foo" "output/bar" "output/baz qux moz"
#
# SSH examples:
#
#   These examples assume that your website is located in a
#   directory named "public_html" on a server named "host"
#   that is accessible by a user named "user" via SSH or SFTP.
#
#   uploader: scp -prC <%= parts %> user@host:public_html
#   uploader: rsync -e ssh -auvz <%= whole %>/ user@host:public_html
#   uploader: lftp sftp://user@host -e 'mirror -Ra --ignore-time <%= whole %>/ public_html; exit'
#
# FTP examples:
#
#   These examples assume that your website is located in a directory
#   named "public_html" on a server named "host" that is accessible
#   by a user named "user" with a password of "password" via FTP.
#
#   uploader: lftp host -u 'user,password' -e 'mirror -Ra --ignore-time <%= whole %>/ public_html; exit'
#
uploader: rsync -avz --delete <%= whole %> snk@rubyforge.org:/var/www/gforge-projects/rassmalog


################################################################################
# Language information
################################################################################


#
# The character set used in your entries.
#
# Examples:
#
#   encoding: utf-8       # Unicode (for all languages)
#   encoding: x-sjis      # Shift JIS (for Japanese only)
#   encoding: x-iscii-te  # Telugu ISCII (for Telugu only)
#
encoding: utf-8


#
# The ISO-639 code and (optionally) the ISO-3166 country
# code for the primary language used in your entries.
#
# For a list of ISO-639 language codes, see:
#
#   http://en.wikipedia.org/wiki/List_of_ISO_639-2_codes
#
# For a list of ISO-3166 country codes, see:
#
#   http://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#Current_codes
#
# Examples:
#
#   language: en    # English
#   language: en-us # English (United States)
#   language: en-gb # English (Great Britain)
#
language: en-us


################################################################################
# Blog generation
################################################################################


#
# Path to a file in the output/ directory that should be displayed when
# somebody visits your blog. This is called the "front page" of your blog.
#
# To have an automatic listing of the most recent entries
# on the front page, simply leave this parameter blank:
#
#   front_page:   # nothing here!
#
front_page: rassmalog/welcome.html


#
# Maximum number of recent entries to display on the front page.
#
# If you want all entries to be displayed on the front page (without
# a maximum limit), then simply leave this parameter blank:
#
#   recent_entries:   # nothing here!
#
recent_entries: 5


#
# Controls whether entries are summarized in tag
# pages, archive pages, and the recent entries page.
#
# The config/entry.erb template controls how an entry
# is summarized.  By default, only the first paragraph
# of an entry is shown when summarization is enabled.
#
# To disable this parameter, set its value to "false" like this:
#
#   summarize_entries: false
#
summarize_entries: true


#
# Controls whether a table of contents is
# generated, by default, for all blog entries.
#
# A blog entry can override this parameter by specifying
# its own "table_of_contents" parameter in its source file.
#
table_of_contents: true


#
# Controls how frequently archives are created.
#
# To have one archive per unique year, specify:
#
#   archive_frequency: %Y
#
# To have one archive per unique month, specify:
#
#   archive_frequency: %Y-%m
#
# To have one archive per unique day, specify:
#
#   archive_frequency: %Y-%m-%d
#
# To have one archive per some other criteria, specify your own value:
#
#   archive_frequency: put your own value here
#
# For more information, see the documentation of the Time.strftime method:
#
#   http://www.rubycentral.com/pickaxe/ref_c_time.html#Time.strftime
#
archive_frequency: %B %Y



################################################################################
# Other content
################################################################################


#
# Hierarchical menu of links.
#
# By default, this menu is shown in all generated HTML pages.
# To change this behavior, edit the config/html.erb template.
#
# You can use eRuby directives in both the NAME and URL
# portions (left- and right-hand sides of the equation).
#
# In addition, the NAME portion will be converted into HTML using
# the standard mechanism defined in the config/format.rb file.
#
menu:
  - Rassmalog:
    - What's new?: <%= TAGS['history'].first.url %>
    - Tips & tricks: <%= TAGS['tricks'].url %>
    - Announcements: rss.xml
    - Project home: http://rassmalog.rubyforge.org
    - Project portal: http://rubyforge.org/projects/rassmalog/

  - Documentation:
    - Example entry: rassmalog/example.html
    - API reference: ../ref/index.html
    - Textile syntax: http://hobix.com/textile/
    - YAML syntax: http://yaml4r.sourceforge.net/cookbook/
    - eRuby syntax: http://www.ruby-doc.org/docs/ProgrammingRuby/html/web.html#S2

  - Facilities:
    - Source code: http://rassmalog.rubyforge.org/src/rassmalog/
    - Downloads: http://rubyforge.org/frs/?group_id=2737
    - Bugs: http://rubyforge.org/tracker/?group_id=2737
    - Patches: http://rubyforge.org/tracker/?group_id=2737
    - Requests: http://rubyforge.org/tracker/?group_id=2737
    - Forums: http://rubyforge.org/forum/?group_id=2737

  - Users:
    - Future:
      - Add your blog here!: <%= BLOG.email.to_url('add Rassmalog user blog', 'Hi, my blog URL is ________') %>

    - Present:
      - Suraj N. Kurapati: http://rassmalog.rubyforge.org/blog/
      - Josef 'Jupp' Schugt: http://www.mynetcologne.de/~nc-schugtjo/blog/
      - Asterisell: http://asterisell.profitoss.com
      - Profitoss: http://profitoss.com
      - ClothRed: http://clothred.rubyforge.org
      - Fox Chao: http://blog.netinfox.com
      - Shane Sveller: http://shanesveller.com
      - Hemant Kumar: http://gnufied.org
      - Dave Scotto: http://www.yasgursfarm.us/d/

    - Past:
      - Manfred Schreiweis: http://blog.mabitoka.de
      - Rasmus Arnling Bååth: http://www.sumsar.net
      - Matthew Routley: http://matt.routleynet.org/blog/
      - David Karapetyan: http://www-scf.usc.edu/~dkarapet/blog/

  - hey!:
    - this menu is:
      - hierarchical!:
        - 1:
          - 2:
            - 3...
