##
## This is the primary configuration file for your blog.
##


################################################################################
# Blog information
################################################################################


#
# The name of your blog.
#
name: Put the name of your blog here


#
# Description of your blog.
#
info: |
  Describe your blog here. <br/>
  Fill as many lines as you need!


################################################################################
# Author information
################################################################################


#
# The name of the blog author.
#
author: Put your name here


#
# The e-mail address that will receive comments about your blog entries.
#
# This address will be obfuscated into HTML entities so that e-mail address
# harvesters won't bother to figure out what it is. For example, the address
# "xxx@yyy.zzz" will be converted into the following *before* it is written
# to a HTML file:
#
#   &#120;&#120;&#120;&#64;&#121;&#121;&#121;&#46;&#122;&#122;&#122;
#
# If you do not wish to receive comments about your blog entries, or if you
# absolutely *do not* want your e-mail address to be included in the output
# (even in the obfuscated form), then you can simply leave this parameter
# blank, as follows:
#
#   email:   # nothing here!
#
# Examples:
#
#   email: your+rassmalog@email.here
#   email: your+comments@email.here
#   email: your+blog@email.here
#   email: your@email.here
#
email: your@email.here


################################################################################
# Publishing information
################################################################################


#
# The URL of your published blog.
#
# Examples:
#
#   url: http://your.host.com/~you/path/to/your/blog/
#   url: http://you.your_host.com/
#
url: http://your.host.com/~you/path/to/your/blog/


#
# The rsync or SSH address of your published blog.
#
# If you use a tool other than rsync to upload your blog,
# then you can either:
#
# 1. change the "uploader" parameter (see below) to
#    accomodate your file uploading software.
#
# 2. don't bother with this feature. Just use
#    some other means to upload your blog.
#
# Syntax:
#
#   user@host:relative/path/to/home/directory/
#   user@host:/absolute/path/from/root/directory/
#
# Examples:
#
#   host: you@your_host:path/to/your/blog/
#
host: you@your_host:path/to/your/blog/


#
# The command that uploads your blog to your website.
#
# Two arguments are passed to this command:
# 1. The directory that needs to be uploaded.
# 2. The value of the "host" parameter (see above).
#
# Examples:
#
#   uploader: rsync --rsh=ssh -auvz
#   uploader: scp -Cr
#
uploader: rsync --rsh=ssh -auvz


################################################################################
# Language information
################################################################################


#
# The character set used in your entries.
#
# Examples:
#
#   encoding: utf-8       # Unicode (for all languages)
#   encoding: x-sjis      # Shift JIS (for Japanese only)
#   encoding: x-iscii-te  # Telugu ISCII (for Telugu only)
#
encoding: utf-8


#
# The ISO-639 code and (optionally) the ISO-3166 country code for the
# primary language used in your entries.
#
# For a list of ISO-639 language codes, see:
#
#   http://en.wikipedia.org/wiki/List_of_ISO_639-2_codes
#
# For a list of ISO-3166 country codes, see:
#
#   http://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#Current_codes
#
# Examples:
#
#   language: en    # English
#   language: en-us # English (United States)
#   language: en-gb # English (Great Britain)
#
language: en-us


################################################################################
# Blog generation
################################################################################


#
# Name of a file in the output/ directory that is displayed when somebody
# visits your blog. This is called the "front page" of your blog.
#
# To have an automatic listing of the most recent entries on the front page,
# simply leave this parameter blank:
#
#   front_page:   # nothing here!
#
front_page: 2006-12-13-welcome-to-rassmalog.html


#
# Maximum number of recent entries to display on the front page.
#
recent_entries: 3


#
# Specifies whether entries are summarized in tag and archive pages.
#
# The config/entry.erb template controls how an entry is summarized. By
# default, only the first paragraph of an entry is shown when summarization
# is enabled.
#
# To disable this parameter, set its value to "false" like this:
#
#   summarize_entries: false
#
summarize_entries: true


#
# Controls how frequently archives are created.
#
# To have one archive per unique year, specify:
#
#   archive_frequency: %Y
#
# To have one archive per unique month, specify:
#
#   archive_frequency: %Y-%m
#
# To have one archive per unique day, specify:
#
#   archive_frequency: %Y-%m-%d
#
# To have one archive per some other criteria, specify your own value:
#
#   archive_frequency: put your own value here
#
# For more information, see the documentation of the Time.strftime method:
#
#   http://www.rubycentral.com/book/ref_c_time.html#Time.strftime
#
archive_frequency: %B %Y



################################################################################
# Other content
################################################################################


#
# Hierarchical menu of links. By default, this menu is shown in all generated
# HTML pages. To disable this behavior, edit the config/html.erb template.
#
menu:
  - Rassmalog:
    - What's new?: index_entries.html
    - Tips & tricks: tricks.html
    - Announcements: rss.xml
    - Project home: http://rassmalog.rubyforge.org
    - Project portal: http://rubyforge.org/projects/rassmalog/
    - Author's blog: http://www.soe.ucsc.edu/~snk/

  - Documentation:
    - Example entry: 2006-12-08-put-the-name-of-your-entry-here..html
    - API reference: ../ref/index.html
    - Textile syntax: http://hobix.com/textile/
    - YAML syntax: http://yaml4r.sourceforge.net/cookbook/
    - ERB syntax: http://www.ruby-doc.org/docs/ProgrammingRuby/html/web.html#S2

  - Facilities:
    - Source code: http://rassmalog.rubyforge.org/src/rassmalog/
    - Downloads: http://rubyforge.org/frs/?group_id=2737
    - Bugs: http://rubyforge.org/tracker/?group_id=2737
    - Patches: http://rubyforge.org/tracker/?group_id=2737
    - Requests: http://rubyforge.org/tracker/?group_id=2737
    - Forums: http://rubyforge.org/forum/?group_id=2737

  - hey! this:
    - menu is:
      - hierarchical!:
        - O RLY?:
          - YA RLY!:
            - NO WAI: http://slashdot.org
