##
## This is the primary configuration file for your blog.
##


#
# The name of your blog.
#
name: Put the name of your blog here

#
# Description of your blog.
#
info: |
  Describe your blog here.
  Fill as many lines as you need!

#
# The name of the blog author.
#
author: Put your name here

#
# The URL of your published blog.
#
url: http://your.host.com/~you/path/to/your/blog/

#
# The rsync or SSH address of your published blog.
#
# If you use a tool other than rsync to upload your blog,
# then you don't need to bother with this feature. Instead,
# you can manually upload the generated blog files.
#
# Examples:
#
#   user@host:path/relative/to/home/directory/
#   user@host:/absolute/path/from/root/directory/
#
host: you@your_host:path/to/your/blog/


#
# The character set used in your entries.
#
# Examples:
#
#   encoding: utf-8       # Unicode (for all languages)
#   encoding: x-sjis      # Shift JIS (for Japanese only)
#   encoding: x-iscii-te  # Telugu ISCII (for Telugu only)
#
encoding: utf-8

#
# The primary language used in your entries.
# See http://www.html-reference.com/language.htm for syntax.
#
# Examples:
#
#   language: en-us # English (United States)
#   language: ja-jp # Japanese (Japan)
#   language: te-in # Telugu (India)
#
language: en-us

#
# Maximum number of entries to display on the front page.
#
index: 3

#
# Specifies whether entries are summarized in tag and archive pages.
#
# To disable this option, set the value to "false" like this:
#
#   summarize: false
#
summarize: true


#
# Hierarchical navigation menu shown in all generated HTML pages.
#
menu:
  - Rassmalog:
    - Home page: http://rassmalog.rubyforge.org
    - Project portal: http://rubyforge.org/projects/rassmalog/
    - Facilites:
      - Source code: http://rassmalog.rubyforge.org/src/rassmalog/
      - Downloads: http://rubyforge.org/frs/?group_id=2737
      - Bugs: http://rubyforge.org/tracker/?group_id=2737
      - Patches: http://rubyforge.org/tracker/?group_id=2737
      - Requests: http://rubyforge.org/tracker/?group_id=2737
      - Forums: http://rubyforge.org/forum/?group_id=2737
    - Author's blog: http://www.soe.ucsc.edu/~snk/

  - Reference:
    - Textile syntax: http://hobix.com/textile/
    - ERB templates: http://www.ruby-doc.org/docs/ProgrammingRuby/html/web.html#S2
    - Learn YAML in 5 minutes: http://yaml.kwiki.org/?YamlInFiveMinutes
    - YAML cookbook: http://yaml4r.sourceforge.net/cookbook/

  - hey! this:
    - menu is:
      - hierarchical!:
        - O RLY?:
          - YA RLY!:
            - NO WAI: http://slashdot.org
