# de - German
About: Über
About %s: Über %s
Archives: Archive
Author: Autor
Comments: Anmerkungen
Contents: Inhalt
Date: Datum
Entries: Einträge
First: Zuerst
Generator: Generator
Home: Haus
Icons: Ikonen
Last: Letztes
Name: Name
Next: Zunächst
Permanent hyperlink to this section: Dauerhaftes Hyperlink zu diesem Abschnitt
Previous: Vorhergehend
RSS feed: RSS Zufuhr
Read more...: Mehr...
Return to %s: Gehen Sie zu %s zurück
Search: Suche
Size: Größe
Sorted by %s: Sortiert durch %s
Subscribe: Abonnieren
Tags: Tags
Up: Herauf
You are now being redirected to %s.: Sie werden jetzt zu %s. umadressiert.
You may {send comments by e-mail}.: Sie können {senden Sie Anmerkungen durch eMail}.
