# de - German
About: Über
About %s: Über %s
Archives: Archive
Author: Autor
Comments: Kommentare
Contents: Inhalt
Date: Datum
Entries: Einträge
First: Erster
Generator: Generator
Home: Start
Icons: Bilder 
Last: Letzter
Name: Name
Next: Nächster
Permanent hyperlink to this section: Permalink zu diesem Eintrag
Previous: Vorheriger
RSS feed: RSS Feed
Read more...: Mehr...
Return to %s: Zurück zu %s
Search: Suche
Size: Größe
Sorted by %s: Sortiert nach %s
Subscribe: Abonnieren
Tags: Tags
Up: Ebene höher
You are now being redirected to %s.: Sie werden jetzt zu %s. weitergeleitet.
You may {send comments by e-mail}.: Sie können {Kommentare per Email senden}.
