# es - Spanish
About: Sobre
About %s: Sobre %s
Archives: Archivos
Author: Autor
Comments: Comentarios
Contents: Contenido
Date: Fecha
Entries: Entradas
First: Primero
Generator: Generador
Home: Hogar
Icons: Iconos
Last: Último
Name: Nombre
Next: Después
Previous: Anterior
RSS feed: Alimentación de RSS
Read more...: Lea más...
Search: Búsqueda
Size: Tamaño
Sorted by %s: Clasificado por %s
Subscribe: Suscriba
Tags: Etiquetas
Up: Encima de
You are now being redirected to %s.: Le ahora están volviendo a dirigir a %s.
You may {send comments by e-mail}.: Usted puede {envíe los comentarios por el email}.
