# fr - French
About: Au sujet de
About %s: Au sujet du %s
Archives: Archives
Author: Auteur
Comments: Commentaires
Contents: Contenu
Date: Date
Entries: Entrées
First: Premier
Generator: Générateur
Home: Accueil
Icons: Icônes
Last: Dernier
Name: Nom
Next: Suivant
Permanent hyperlink to this section: Lien hypertexte permanent liant cette section
Previous: Précédent
RSS feed: Flux RSS
Read more...: Lire la suite...
Return to %s: Revener à %s
Search: Recherche
Size: Taille
Sorted by %s: Triées par %s
Subscribe: Souscriver
Tags: Étiquette
Up: Monter dans la hiérarchie du site
You are now being redirected to %s.: Vous êtes maintenant redirigé vers %s.
You may {send comments by e-mail}.: Vous pouvez {envoyer un commentaire par courriel}.
