# fr - French
About: A propos de
About %s: A propos de %s
Archives: Archives
Author: Auteur
Comments: Commentaires
Contents: Contenu
Date: Date
Entries: Entrées
First: Premier
Generator: Générateur
Home: Accueil
Icons: Icônes
Last: Dernier
Name: Nom
Next: Suivant
Permanent hyperlink to this section: Lien hypertexte permanent à cette section
Previous: Précédent
RSS feed: Fil RSS
Read more...: La suite...
Return to %s: Retour à %s
Search: Recherche
Size: Taille
Sorted by %s: Trié par %s
Subscribe: S'abonner
Tags: Étiquettes
Up: Début des entrées
You are now being redirected to %s.: Vous êtes maintenant redirigé vers %s.
You may {send comments by e-mail}.: Vous pouvez {envoyer des commentaires par courriel}.
