# fr - French
About: Au sujet de
About %s: Au sujet de %s
Archives: Archives
Author: Auteur
Comments: Commentaires
Contents: Contenu
Date: Date
Entries: Entrées
First: D'abord
Generator: Générateur
Home: Maison
Icons: Icônes
Last: Bout
Name: Nom
Next: Après
Permanent hyperlink to this section: Lien hypertexte permanent à cette section
Previous: Précédent
RSS feed: Alimentation de RSS
Read more...: Lisez plus...
Return to %s: Revenez à %s
Search: Recherche
Size: Taille
Sorted by %s: Assorti par %s
Subscribe: Souscrivez
Tags: Étiquettes
Up: Vers le haut de
You are now being redirected to %s.: Vous maintenant êtes réorienté à %s.
You may {send comments by e-mail}.: Vous pouvez {envoyez les commentaires par l'email}.
