# it - Italian
About: Circa
About %s: Circa %s
Archives: Archivi
Author: Autore
Comments: Osservazioni
Contents: Soddisfare
Date: Data
Entries: Entrate
First: In primo luogo
Generator: Generatore
Home: Casa
Icons: Icone
Last: Ultimo
Name: Nome
Next: Dopo
Permanent hyperlink to this section: Hyperlink permanente a questa sezione
Previous: Precedente
RSS feed: Alimentazione di RSS
Read more...: Legga più...
Return to %s: Rinvii a %s
Search: Ricerca
Size: Formato
Sorted by %s: Fascicolato da %s
Subscribe: Abboni
Tags: Modifiche
Up: Su
You are now being redirected to %s.: Ora state riorientando a %s.
You may {send comments by e-mail}.: Potete {invii le osservazioni dal email}.
