# nl - Dutch
About: Ongeveer
About %s: Ongeveer %s
Archives: Archieven
Author: Auteur
Comments: Commentaren
Contents: Inhoud
Date: Datum
Entries: Ingangen
First: Eerst
Generator: Generator
Home: Huis
Icons: Pictogrammen
Last: Duur
Name: Naam
Next: Daarna
Permanent hyperlink to this section: Permanente hyperlink aan deze sectie
Previous: Vorig
RSS feed: Voer RSS
Read more...: Lees meer...
Return to %s: Terugkeer naar %s
Search: Zoek
Size: Grootte
Sorted by %s: Gesorteerd door %s
Subscribe: Teken in
Tags: Markeringen
Up: Op
You are now being redirected to %s.: U wordt nu opnieuw gericht aan %s.
You may {send comments by e-mail}.: U kunt {verzend commentaren per e-mail}.
