# pt - Portuguese
About: Sobre
About %s: Sobre %s
Archives: Arquivos
Author: Autor
Comments: Comentários
Contents: Índices
Date: Data
Entries: Entradas
First: Primeiramente
Generator: Gerador
Home: Repouso
Icons: Ícones
Last: Último
Name: Nome
Next: Em seguida
Previous: Precedente
RSS feed: Alimentação de RSS
Read more...: Leia mais...
Search: Busca
Size: Tamanho
Sorted by %s: Classificado por %s
Subscribe: Subscreva
Tags: Tag
Up: Acima de
You are now being redirected to %s.: Você está sendo reorientado agora a %s.
You may {send comments by e-mail}.: Você pode {emita comentários pelo email}.
