# ru - Russian
About: О
About %s: О %s
Archives: Архивохранилища
Author: Автор
Comments: Комментарии
Contents: Содержание
Date: Дата
Entries: Входы
First: Во первых
Generator: Генератор
Home: Дом
Icons: Иконы
Last: Последнее
Name: Имя
Next: Затем
Previous: Предыдуще
RSS feed: Питание RSS
Read more...: Прочитайте больше...
Search: Поиск
Size: Размер
Sorted by %s: Сортировано %s
Subscribe: Подпишитесь
Tags: Бирки
Up: Вверх по
You are now being redirected to %s.: Вы теперь перенаправляетесь к %s.
You may {send comments by e-mail}.: Вы можете {пошлите комментарии электронной почтой}.
