# te - Telugu
About: గుఱించి
About %s: %s గుఱించి
Archives: చరిత్రం
Author: లేఖరి
Comments: అభీప్రాయములు
Contents: సూచిక
Date: తేది
Entries: లేఖలు
First: మొదలు
Generator: చేఁత
Home: ఇల్లు
Icons: బొమ్మలు
Last: చివర
Name: పేరు
Next: తరువాత
Permanent hyperlink to this section: ఈ భాగముని నిత్యచిరునామ
Previous: క్రితం
RSS feed: RSS ప్రకటణ
Read more...: ఇంక చదువు ...
Return to %s: %s వద్దకు తిరిగివెళ్లు
Search: వెతుకు
Size: కొలత
Sorted by %s: %s బట్టి  ఏర్పఱుచినవి
Subscribe: ప్రకటణ
Tags: తరము
Up: పైకి
You are now being redirected to %s.: మిమ్మల్ని %s వయపు పంపుతున్నాము.
You may {send comments by e-mail}.: ఈమేల్ ద్వారా {మీ అభీప్రాయము తెలియజేయగలరు}.
