# zt - Chinese-trad
About: 關於
About %s: 關於%s
Archives: 檔案
Author: 作者
Comments: 評論
Contents: 内容
Date: 日期
Entries: 詞條
First: 首先
Generator: 發電器
Home: 家
Icons: 像
Last: 為時
Name: 名字
Next: 其次
Permanent hyperlink to this section: 對這個部分的永久超鏈接
Previous: 早先
RSS feed: RSS飼料
Read more...: 讀更多...
Return to %s: 回到%s
Search: 查尋
Size: 大小
Sorted by %s: 排序由%s
Subscribe: 訂閱
Tags: 標記
Up: 上面
You are now being redirected to %s.: 您現在被改方向對%s。
You may {send comments by e-mail}.: 您可以{由電子郵件寄发評論}。
